### ISSUE TITLE
Need help regrding multi-speaker longform speech generation

### ISSUE THREAD

**Issue by blueprintparadise** [shivammehta25/Matcha-TTS#38]
Could you provide some resources for a long-form speech generation code that allows for switching between multiple speakers within the same text similar to what you did in the youtube video.

**Comment by shivammehta25** [comment]
Hello! Thank you for your interest in 🍵 Matcha-TTS.

This is a great idea, however I do not have a straightforward interface to do it currently. But you can pass two additional lists one of speaker IDs and a list of tuples of their phone boundaries. Later once you pass speaker IDs through the speaker encoder and obtain speaker representations, instead of, broadcasting it for all x, just broadcast only for the specific word boundaries here

https://github.com/shivammehta25/Matcha-TTS/blob/c8d0d60f87147fe340f4627b84588e812e5fbb00/matcha/models/components/text_encoder.py#L403

and in the decoder.

https://github.com/shivammehta25/Matcha-TTS/blob/c8d0d60f87147fe340f4627b84588e812e5fbb00/matcha/models/components/decoder.py#L387

Hopefully this helps :)

**Comment by shivammehta25** [comment]
Hello, I am assuming you are happy with the answer for now, please feel free to reopen the issue and continue the discussions in case of any further points.
