### ISSUE TITLE
Could you explain transformations before applying MAS?

### ISSUE THREAD

**Issue by Subuday** [shivammehta25/Matcha-TTS#55]
Could you explain intuition behind these lines of code? What formulas does it refer? In Glow-TTS I've found only description precisely algo of MAS, but not these transformations....

<img width="737" alt="image" src="https://github.com/shivammehta25/Matcha-TTS/assets/46067553/c5f00905-82f0-4c34-a222-da0fa89cf3db">

**Comment by shivammehta25** [comment]
Hello, 

This is to compute the log-likelihood for a given data point under a multivariate isotropic Gaussian distribution with mean `mu_x`.
Log-likelihood is numerically stable to compute than just likelihood as probabilities for very small numbers can cause underflow when multiplied together. Also, log transformation helps to transform multiplication in the linear domain to a summation which is faster to compute. 

Hope this helps,
Regards,
Shivam

**Comment by Subuday** [comment]
Could you please provide maybe some references of formula or smth that gives me more intuition around this code, please?

**Comment by shivammehta25** [comment]
It is similar to the one in Glow-TTS, https://github.com/jaywalnut310/glow-tts/issues/72#issuecomment-1385276411 just x_logs is constant (1) here. 

More info about it can be: https://stats.stackexchange.com/questions/351549/maximum-likelihood-estimators-multivariate-gaussian
Since, this implementation is same as grad-tts the authors there provide a very good explanation regarding this: 
https://github.com/huawei-noah/Speech-Backbones/issues/18

**Comment by Subuday** [comment]
Thanks
