### ISSUE TITLE
multi speaker model doesnt seem to pause well between sentences, compared with the single speaker model

### ISSUE THREAD

**Issue by malaccan** [shivammehta25/Matcha-TTS#67]
i noticed that the single model (LJ Speech) works very well, with natural pauses between words or sentences. however, the multiple speaker model (VCTK) seems to just talk through all the words, with limited pauses. this applies to all speaker ids.

this is easily replicable from the spaces demo when inputting multiple sentences to compare.

is this a known issue? is there a way round this so that the multi speaker model can work as well as the single model?

**Comment by shivammehta25** [comment]
I think this is because of my Naïve preprocessing of the VCTK corpus and the VCTK corpus itself. VCTK doesn't really have a lot of pauses in the middle of sentences, they are single utterances pronounced by multiple speakers. The model learns to mimic that and, thus doesn't learn good pause durations. To improve upon it you might want to train it on a better dataset (which I might do as well but not sure when).

Regards,
Shivam
