### ISSUE TITLE
Number of iteration (steps)

### ISSUE THREAD

**Issue by eladc-git** [shivammehta25/Matcha-TTS#76]
Hi, thanks for the great work.
I wonder, why the number of iterations barely affects the result.
Even for n_timestamps=1, the sound is very good and the improvement of more iterations is unclear.

Thanks, Elad

**Comment by shivammehta25** [comment]
Hey @eladc-git,

This is mainly due to the effectiveness of condition flow matching in solving the vector field and training it for long enough to approximate it nicely. The idea of OT-CFM is derived from this paper: https://arxiv.org/abs/2210.02747. In this paper, they do explain and reason why it is faster and nicer. 
Practically speaking, if you listen to many n_timestamps=1 samples you will hear voice crackling in certain regions, which starts to fade as you increase the iterations. [In our paper](https://arxiv.org/abs/2309.03199), we ablated multiple conditions and reported results. 

Hope that helps!
Shivam
