### ISSUE TITLE
Hi, why matcha-tts choose forward() function to calculate duration of phonemes? And why do not choose synthesise() function? 

### ISSUE THREAD

**Issue by zdj97** [shivammehta25/Matcha-TTS#93]
And could you explain what is the reason to calculate phoneme duration?
Thanks!

**Comment by shivammehta25** [comment]
synthesise() generates from the duration predictor. While the forward function creates a similarity map between the input text and reference mel spectrogram. You can try to use forward when you do not have a reference mel spectrogram. But since we have the mel spectrograms it is more consistent to generate from the reference mels.

**Comment by zdj97** [comment]
Yep! Copy that.
